//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gigi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public string Text { get; set; }
        public int Type { get; set; }
        public int Users { get; set; }
        public int Status { get; set; }
    
        public virtual Status Status1 { get; set; }
        public virtual TypeOrder TypeOrder { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
